services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # Porta para acesso à API do MinIO
      - "9001:9001"  # Porta para o console web do MinIO
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - code-with-data

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootmysql
      - MYSQL_DATABASE=antaq
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - code-with-data

networks:
  code-with-data:
    driver: bridge

volumes:
  minio_data:
  mysql_data:
